### ISSUE TITLE
Bug Report: Not able to pull Docker image nor Helm chart

### ISSUE THREAD

**Issue by germelindam** [DevoteamNL/opendora#123]
### Description

After following the deployment guide from [here](https://github.com/DevoteamNL/opendora/blob/main/devlake-go/DEPLOYMENT.md), I created a PAT with all necessary permissions but when I tried to pull the helm chart or docker image I was not authorized to pull. Docker login is successful.

### Expected behavior

Should be able to pull the Docker image and Helm chart successfully.

### Actual Behavior

- Error: GET "https://ghcr.io/v2/devoteamnl/opendora/open-dora-helm-chart/tags/list": unexpected status code 403: denied: permission_denied: read_package"
- Error response from daemon: denied

### Reproduction steps

- Follow the Deployment guide
- Create Github PAT 
- Pull Docker Image/Helm chart

### Have you spent some time to check if this bug has been raised before?

- [x] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by duke-b** [comment]
@germelindam there was an issue with availability. You should be able to access helm charts now as intended.
Please let me know if there is still an issue with this.
