### ISSUE TITLE
[OPS] README improvements

### ISSUE THREAD

**Issue by kylejwatson** [DevoteamNL/opendora#125]
- Badges to point at main
- Overall explanation (maybe diagram)
- Specify that the plugin install is within the backstage code
- Specify backstage installation as a prerequisite

**Comment by kylejwatson** [comment]
Fixing workflow badges to point to main runs: https://github.com/DevoteamNL/opendora/pull/126

**Comment by goposky** [comment]
Fixed via #130 and released together with 0.2.2.
