### ISSUE TITLE
[OPS] Restructure and enhance README

### ISSUE THREAD

**Issue by jeroenvandermeulen** [DevoteamNL/opendora#166]
- Improve CONTRIBUTING.md
- Add Devlake install guide for dev and prod (dev currently being automated in issue #136)
- Add Security.md
- Add used version for backstage-plugin node and yarn

**Comment by goposky** [comment]
@jeroenvandermeulen what is the status of this story?

**Comment by jeroenvandermeulen** [comment]
Finished this in PR #166!
