### ISSUE TITLE
[OPS] Helm Chart for deploying Apache DevLake and the DORA API

### ISSUE THREAD

**Issue by brunocribeiro** [DevoteamNL/opendora#45]
Depends on: https://github.com/DevoteamNL/opendora/issues/47

As an OpenDORA operator (an operational user that will deploy the solution)

I would like to have a Helm chart for OpenDORA

So that I can use it to deploy the API as a container and also 

The following deliverables are expected:

- a Helm chart is created, with a deployment that deploys both the OpenDORA API and Apache DevLake
  - https://github.com/apache/incubator-devlake-helm-chart should be used as a dependency
- a GitHub action is created to package and publish the chart to a Helm registry (TBD)

References:

- https://devlake.apache.org/docs/v0.18/GettingStarted/HelmSetup
- https://github.com/apache/incubator-devlake-helm-chart

**Comment by goposky** [comment]
@brunocribeiro could u the branch u'd been working on please? And we'll take it from there.

**Comment by brunocribeiro** [comment]
> @brunocribeiro could u the branch u'd been working on please? And we'll take it from there.

@goposky unassigning it as it's better to start it from scratch. What was done is not even half-complete. Thanks

**Comment by goposky** [comment]
We agreed that we will focus on just the Opendora API helm chart. For now we do not need to provide a separate helm chart for Devlake.

**Comment by kylejwatson** [comment]
https://github.com/DevoteamNL/opendora/pull/113 
Removed the devlake dependency, added deployment documentation, added a publishing workflow.
