### ISSUE TITLE
[FE] Label for Lead time for changes description

### ISSUE THREAD

**Issue by kylejwatson** [DevoteamNL/opendora#95]
As an OpenDORA Backstage Plugin user

I would like to be able to see a summary of the lead time for changes metric.

So that I can quickly understand performance.

**Comment by goposky** [comment]
Hi @kylejwatson what is the status of this story?

**Comment by kylejwatson** [comment]
> Hi @kylejwatson what is the status of this story?

I may be mistaken, but I think this was related to this summary:
![image](https://github.com/DevoteamNL/opendora/assets/5176836/1dd9c542-d293-4b2b-816c-38c05251f80f)
I think it has been implemented based on the screenshot in the readme. I will have to find some time to have a look though.

**Comment by kylejwatson** [comment]
> > Hi @kylejwatson what is the status of this story?
> 
> I may be mistaken, but I think this was related to this summary: ![image](https://private-user-images.githubusercontent.com/5176836/330062169-1dd9c542-d293-4b2b-816c-38c05251f80f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDY2OTgsIm5iZiI6MTcxNTYwNjM5OCwicGF0aCI6Ii81MTc2ODM2LzMzMDA2MjE2OS0xZGQ5YzU0Mi1kMjkzLTRiMmItODE2Yy0zOGMwNTI1MWY4MGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTNUMTMxOTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzI3YzMzZDZjZDEwOWJmYTdmOTM1NWYxNTRhOTg4M2RhOTE2ODg2MTU4M2QxNjc4OWU0OTg0ZjAzMjQ4ODU5MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1PNGcLGeQuMx-nIQvvs06i_DP5A-04DTzZFttsSSt3I) I think it has been implemented based on the screenshot in the readme. I will have to find some time to have a look though.

Issue number wasn't added unfortunately so I think this was missed: https://github.com/DevoteamNL/opendora/pull/132 will close now
